const char bmflash_help[] = {
  "# BlackMagic Flash Programmer\n"
  "\n"
  "This utility downloads firmware into a micro-controller using the\n"
  "Black Magic Probe. It automatically handles idiosyncrasies of some microcontroller\n"
  "families, and supports setting a serial number during the download (i.e. serialization).\n"
  "\n"
  "At the top of the main window, you can select the ELF file to download into the\n"
  "microcontroller. Below that, are panels for general options and serialization\n"
  "settings.\n"
  "\n"
  "To start a download, you can also use function key F5.\n"
  "\n"
  "More information:\n"
  " [[Options]]\n"
  " [[Serialization]]\n"
  " [[Tools]]\n"
  " [[About BlackMagic Flash Programmer]]\n"
  "\n"
  "# Options\n"
  "\n"
  "Various options can be set for the target. These options are linked to the ELF\n"
  "file that is selected. So you can use different options for separate projects.\n"
  "\n"
  "*Black Magic Probe*\n"
  ": This field is typically pre-selected, if you only have a single probe connected\n"
  " to USB. When you have multiple probes connected at the same time, you need to\n"
  " select the appropriate one from the drop-down list.\n"
  "\n"
  ": If you have a ctxLink probe configured for Wi-Fi, you need to select \"TCP/IP\"\n"
  " from the drop-down list.\n"
  "\n"
  "*IP Address*\n"
  ": This option is only visible when \"TCP/IP\" is selected from the drop-down list\n"
  " of the \"Black Magic Probe\" option. Here, you can fill in the IP address that\n"
  " the debug probe (likely a ctxLink probe) is configured at. Alternatively,\n"
  " you can click on the \"...\" button at the right of the edit field, to let the\n"
  " utility scan the network for the debug probe.\n"
  "\n"
  "*MCU Family*\n"
  ": The microcontroller family must be set only for specific micro~controller families\n"
  " that require specific configuration or processing before the download. It is\n"
  " currently needed for the \"LPC\" family by NXP. For other micro~controllers, this\n"
  " field should be set to \"Standard\".\n"
  "\n"
  "*Post-process*\n"
  ": A post-processing script is run after every successful download, with information\n"
  " on the ELF file and the serial number (if serialization) is active. The script\n"
  " must be in the Tcl language. See the book \"Embedded Debugging with the Black Magic Probe\"\n"
  " for more information on scripting.\n"
  "\n"
  "*Power Target*\n"
  ": This option can be set to drive the power-sense pin with 3.3V (to power the\n"
  " target).\n"
  "\n"
  "*Full Flash Erase*\n"
  ": This option erases all Flash sectors in the microcontroller, before proceeding with the\n"
  " download. If not set, only the Flash sectors for which there is new data get\n"
  " erased & overwritten. Note that you can also clear all Flash memory via the\n"
  " Tools button.\n"
  "\n"
  "*Reset target during connect*\n"
  ": This option may be needed on some microcontrollers, especially if SWD pins get redefined.\n"
  "\n"
  "*Keep Log of downloads*\n"
  ": On each successful firmware download, the utility adds a record to a log file,\n"
  " with the date & time of the download, plus information of the ELF file (checksum,\n"
  " RCS \"ident\" string). This is especially useful in combination with serialization,\n"
  " for tracking the firmware version and the date of the download.\n"
  "\n"
  "*Print Download Time*\n"
  ": On completing a download, print the time that the download took (in the Status\n"
  " view).\n"
  "\n"
  "---\n"
  "See also:\n"
  " [[Serialization]]\n"
  " [[Tools]]\n"
  " [[About BlackMagic Flash Programmer]]\n"
  "\n"
  "# Serialization\n"
  "\n"
  "Each firmware download can store an incremental serial number in the firmware.\n"
  "It does this by patching the ELF file on the flight, while it downloads to the\n"
  "target (the original ELF file on disk is not changed).\n"
  "\n"
  "The serialization method is either \"No serialization\", \"Address\" or \"Match\".\n"
  "\n"
  "*No serialization*\n"
  ": Serialization is disabled.\n"
  "\n"
  "*Address*\n"
  ": This option stores the serial number at a specific address.\n"
  "\n"
  ": You specify the name of a section in the ELF file, plus the offset from the\n"
  " start of the section. If you leave the field of the section empty, the offset\n"
  " is relative to the beginning of the ELF file. The offset is interpreted as a\n"
  " hexadecimal value.\n"
  "\n"
  "*Match*\n"
  ": This option searches for a text or byte pattern in the ELF file, and replaces\n"
  " it with the serial number.\n"
  "\n"
  ": You give a pattern to match and an optional prefix. When the pattern is found,\n"
  " it is overwritten by the prefix, immediately followed the serial number.\n"
  "\n"
  ": The match and prefix strings may contain \\\\### and \\\\x## specifications (where\n"
  " \"#\" represents a decimal or hexadecimal digit) for non-ASCII byte values. It\n"
  " may furthermore contain the sequence \\U* to interpret the text that follows as\n"
  " Unicode, or \\A* to switch back to ASCII. When a literal \\\\ is part of the\n"
  " pattern, it must be doubled, as in \\\\\\\\.\n"
  "\n"
  "*Serial*\n"
  ": The serial number is a decimal value. It is incremented after each successful\n"
  " download.\n"
  "\n"
  "*Size*\n"
  ": The size of the serial number is in bytes. The serial number is padded with\n"
  " zeroes to fill up the size. Note that the prefix is part of the size.\n"
  "\n"
  ": For example, if the serial number is 12, the size is 8 and the format is ASCII\n"
  " (and there is no prefix), the string stored is 00000012. But if the format is\n"
  " Unicode, where each character takes two bytes, 0012 would be stored. And if\n"
  " the format is binary, there would be 7 bytes with a zero value stored, followed\n"
  " by a single byte with the value 12.\n"
  "\n"
  "*Format*\n"
  ": The format that the serial number is written in. It can be chosen as binary,\n"
  " ASCII or Unicode. In the latter two cases, the serial number is stored as\n"
  " readable text.\n"
  "\n"
  ": Note that in the case of Unicode text, each character takes two bytes (the size\n"
  " of the serial number is in bytes).\n"
  "\n"
  "*Increment*\n"
  ": The value by which the serial number is incremented after a successful download.\n"
  " It is typically 1, but it may be any value.\n"
  "\n"
  "*File*\n"
  ": By default, the settings for serialization are linked to the ELF file.\n"
  " However, when you want to share the serialization settings (and the serial\n"
  " number sequence) between two or more ELF files, you can specify a file in this\n"
  " field, where the serialization settings will be written to. Note that you need\n"
  " to set this field to the same filename for both projects.\n"
  "\n"
  "# Tools\n"
  "\n"
  "The \"Tools\" button pops up a menu with a few auxiliary actions.\n"
  "\n"
  "*Re-scan Probe List*\n"
  ": If a Black Magic Probe was not detected on start-up, and you connected one\n"
  " afterwards, you may use this option to re-scan for available probes.\n"
  "\n"
  "*Full Flash Erase*\n"
  ": Erase all Flash memory of the target microcontroller.\n"
  "\n"
  "*Erase Option Bytes*\n"
  ": On microcontrollers that support option bytes, you can use this command to\n"
  " clear the option bytes. If Code-Read Protection was set in the option bytes,\n"
  " clearing the option bytes will also erase all Flash memory.\n"
  "\n"
  ": A power-cycle may be required for the microcontroller to reload the option\n"
  " bytes.\n"
  "\n"
  "*Set CRP Option*\n"
  ": On microcontrollers that support Code-Read Protection (e.g. STM32 family),\n"
  " you can set CRP (after downloading the firmware). The Code-Read protection\n"
  " becomes active after a power cycle.\n"
  "\n"
  "# About BlackMagic Flash Programmer\n"
  "\n"
  "The BlackMagic Flash utility is a companion tool of the book \"Embedded Debugging\n"
  "with the Black Magic Probe.\" More information on the utility and its use, can be\n"
  "found in this book. It is available as a free PDF file, and as a printed book.\n"
  "\n"
  "The utility requires a debug probe that is compatible with the Black Magic Probe.\n"
  "It is a self-contained utility; it does not require GDB.\n"
  "\n"
  "---\n"
  "Version 1.2.6897 \\\n"
  "Copyright 2019-2022 CompuPhase \\\n"
  "Licensed under the Apache License version 2.0\n"
  "\n"
};
